### ISSUE TITLE
cannot move config

### ISSUE THREAD

**Issue by hakimarx** [MS-WEB-BN/h4rpy#1]
mkdir: cannot create directory ‘/root/.config’: File exists
mv: cannot move 'config' to '/root/.config/terminator/config': No such file or directory
a@kali:~/h4rpy$ sudo chmod +x h4rpy
a@kali:~/h4rpy$ sudo ./h4rpy 
[*] Starting h4rpy...
ConfigBase::load: Unable to open /root/.config/terminator/config ([Errno 2] No such file or directory: '/root/.config/terminator/config')

(terminator:2863): Gtk-WARNING **: 22:14:59.343: Theme parsing error: gtk.css:2794:15: Not using units is deprecated. Assuming 'px'.
layout does not exist: h4rpy
layout None not defined

**Comment by tripledd** [comment]
- I don't know if this will help, but I rec'd the same errors. I tried changing the config file to go to the kali profile and not root, but still errored out. I was doing this from a terminator terminal already (Already had it installed).
- removed all folders, switched to normal default terminal, redownloaded, ran commands again, this time it worked.

**Comment by MS-WEB-BN** [comment]
@hakimarx due to the error the script encountered when trying to create "/root/.config" directory, creation of "/root/.config/terminator" has failed too ("mkdir /root/.config && mkdir /root/.config/terminator"). The terminator error is a logical follow up for this problem, since no layouts exist. 
For now, you can create the "/root/.config/terminator" manually, and that will solve your problem. Thank you for reporting this, I will change the way it creates directories.  

@tripledd by default configuration, terminator needs configuration files to be in "/root/.config/terminator/" when it is run as root. Since the problem was solved by redownloading, I suppose you've modified the script to move config to different location, and that, as a result of it's movement, config file was not present in h4rpy directory.

Thank you for reporting this, and even though config file is intentionally moved, not copied, I will change it in order to avoid similar problems.
